name: incloud

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        
      - name: Setup Dependencies
        run: sudo apt-get -y install python
        
      - name: Allin scan
        run: |
          wget https://github.com/P1-Team/AlliN/archive/refs/tags/v2.1.8.zip
          unzip v2.1.8.zip
          cp AlliN-2.1.8/AlliN.py AlliN.py
          cat input/actions.txt|while read line; do python AlliN.py $line ;done
          tar -czvf Allinlog.tar.gz output/
          mv Allinlog.tar.gz output/Allinlog.tar.gz
        shell: bash
      - name: Create local changes
        run: |
          git add output/Allinlog.tar.gz
      - name: Commit results to Github
        run: |
          git config --local user.email "1660351753@qq.com"
          git config --global user.name "1660351753"
          git commit -m "InCloud Report" -a --allow-empty
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          
